"""product table

Revision ID: d2461f6e0188
Revises: 97a7e46f647b
Create Date: 2020-03-03 17:43:44.475204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2461f6e0188'
down_revision = '97a7e46f647b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_productss_timestamp', table_name='productss')
    op.drop_table('productss')
    op.drop_index('ix_products_timestamp', table_name='products')
    op.drop_table('products')
    op.add_column('product', sa.Column('category', sa.String(length=140), nullable=True))
    op.add_column('product', sa.Column('rate', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'rate')
    op.drop_column('product', 'category')
    op.create_table('products',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('body', sa.VARCHAR(length=140), nullable=True),
    sa.Column('category', sa.VARCHAR(length=140), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_products_timestamp', 'products', ['timestamp'], unique=False)
    op.create_table('productss',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('body', sa.VARCHAR(length=140), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_productss_timestamp', 'productss', ['timestamp'], unique=False)
    # ### end Alembic commands ###
